gh-209 IterableConcat
gchq/koryphe pull request #210
Opened 2021-01-05 13:24 UTC by GCHQDev404

# Related Issue

- Resolve #209

2021-01-15 09:42 UTC, d47853 requested changes

2021-01-15 09:42 UTC, d47853 commented on core/src/main/java/uk/gov/gchq/koryphe/impl/binaryoperator/IterableConcat.java
> +@Since("1.12.1")
As it's a new feature, it would require a 1.13.0 release
```suggestion
@Since("1.13.0")
```

2021-01-15 09:42 UTC, d47853 commented on core/src/main/java/uk/gov/gchq/koryphe/impl/binaryoperator/IterableConcat.java
> +        return IterableUtil.concat(a, b);
I don't know if it's on the classpath but I think there's an Iterables library somewhere which will do this for us.

2021-05-17 13:25 UTC, GCHQDev404 commented
No longer required

2021-05-17 13:25 UTC, closed without merging