Gh 222 remove closeable
gchq/koryphe pull request #240
Opened 2022-01-25 12:43 UTC by r32575

This PR:
- removes `CloseableIterable`, `CloseableIterator` and all `iterable` classes
- changes all `CloseableIterable` and `CloseableIterator` references to `Iterable`/`Iterator`
- fixes tests

2022-01-25 17:41 UTC, GCHQDev404 requested changes

2022-01-25 17:41 UTC, GCHQDev404 commented on core/src/test/java/uk/gov/gchq/koryphe/tuple/binaryoperator/TupleAdaptedBinaryOperatorCompositeTest.java
> +        final ClassCastException actual = assertThrows(ClassCastException.class,
👍

2022-01-25 17:45 UTC, r32575 commented on core/src/test/java/uk/gov/gchq/koryphe/tuple/binaryoperator/TupleAdaptedBinaryOperatorCompositeTest.java
> +                "\"operators\": [" +
Yeah, the IDE altered them when I saved... I'll redo

2022-01-25 18:18 UTC, r32575 commented on core/src/test/java/uk/gov/gchq/koryphe/tuple/binaryoperator/TupleAdaptedBinaryOperatorCompositeTest.java
> +                "\"operators\": [" +
Reformatted the code

2022-01-25 18:33 UTC, r32575 commented on core/src/main/java/uk/gov/gchq/koryphe/impl/function/CsvToMaps.java
> +        try (final CSVParser csvParser = new CSVParser(new StringReader(csv), getCsvFormat())) {
Not sure that Gaffer is ready to upgrade to Java 11 yet but the change is required it. May be better to create a `Koryphe v2` with the change in for Java 8 and make the change in the #239 or create another issue.

2022-01-31 11:44 UTC, GCHQDeveloper314 commented on core/src/test/java/uk/gov/gchq/koryphe/tuple/binaryoperator/TupleAdaptedBinaryOperatorCompositeTest.java
> +                             "}" +
What's this? It looks to me like the indentation was correct before this change.

2022-01-31 11:49 UTC, GCHQDev404 approved these changes
No Objections

2022-01-31 13:50 UTC, t11947 approved these changes

2022-01-31 13:51 UTC, t11947 commented
We'll stick with the Java 8 syntax for now then.

2022-01-31 16:23 UTC, t92549 commented on core/src/main/java/uk/gov/gchq/koryphe/util/IterableUtil.java
> -    @Deprecated
This is indeed being un-Deprecated and as this PR now fixes or deletes all previously Deprecated code, #237 has been closed

2022-01-31 16:24 UTC, t92549 approved these changes

2022-01-31 16:52 UTC, t92549 commented on core/src/test/java/uk/gov/gchq/koryphe/tuple/binaryoperator/TupleAdaptedBinaryOperatorCompositeTest.java
> +                "\"operators\": [" +
For me it still shows unindented

2022-02-03 16:08 UTC, merged