gh-250 added ability to add to TreeSet within ToSet
gchq/koryphe pull request #252
Opened 2022-03-30 10:34 UTC by p3430233

2022-03-30 17:03 UTC, GCHQDeveloper314 requested changes

2022-03-31 07:30 UTC, p3430233 commented on core/src/main/java/uk/gov/gchq/koryphe/impl/function/ToSet.java
> +            setImpl.add(null);
adding a null to a TreeSet will generate a NullPointerException

2022-03-31 08:47 UTC, GCHQDeveloper314 commented on core/src/main/java/uk/gov/gchq/koryphe/impl/function/ToSet.java
> +            setImpl.add(null);
Ok, the historic behaviour of adding a `null` also seems odd, but that cannot be changed now. I would suggest reformatting the code a little to remove the nested if statement and improve clarity, something like this:
```java
if (implementation.isAssignableFrom(TreeSet.class) && (value == null)) {
  return setImpl;
} else if (implementation.isAssignableFrom(HashSet.class) && (value == null)) {
  setImpl.add(null);
```
Although, in the case where a `HashSet` was used and `value` was `null` the final `if` will add a it anyway. So we don't need to check for `HashSet`. The first `if` can be replaced with just:
```java
if (implementation.isAssignableFrom(TreeSet.class) && (null == value)) {
   return setImpl;
```

2022-03-31 12:28 UTC, t92549 commented on core/src/main/java/uk/gov/gchq/koryphe/impl/function/ToSet.java
> +            throw new IllegalArgumentException("Unrecognised Set implementation");
Test added

2022-03-31 12:29 UTC, t92549 commented on core/src/main/java/uk/gov/gchq/koryphe/impl/function/ToSet.java
> +            setImpl.add(null);
Your second suggestion was used

2022-03-31 12:29 UTC, t92549 commented on core/src/main/java/uk/gov/gchq/koryphe/impl/function/ToSet.java
> +        setImplementation(Class.forName(implementationString));
As far as I understand, both of your examples will use `DEFAULT_IMPLEMENTATION` and I am not sure this is an issue?

2022-03-31 13:07 UTC, GCHQDeveloper314 commented on core/src/main/java/uk/gov/gchq/koryphe/impl/function/ToSet.java
> +        setImplementation(Class.forName(implementationString));
I've just tested it (with the code as it was when I added the comment) and the first one throws an exception, the second one doesn't. This has been fixed as the latest commit by @p3430233 removes the wrapped `Class.forName()` and so there is no longer an exception thrown and the behaviour is consistent.

2022-03-31 13:07 UTC, GCHQDeveloper314 approved these changes

2022-03-31 13:26 UTC, t92549 commented on core/src/test/java/uk/gov/gchq/koryphe/impl/function/ToSetTest.java
>      @Override
You could add the implementation field to `shouldJsonSerialiseAndDeserialise` test to make sure it works as expected

2022-04-01 12:29 UTC, t92549 approved these changes

2022-04-01 12:29 UTC, merged