Gh-303: Update Spotbugs
gchq/koryphe pull request #304
Opened 2023-01-23 14:02 UTC by GCHQDeveloper314

# Related Issue

- Resolve #303

2023-01-23 15:25 UTC, lb324567 commented on code-style/spotbugs-exclude.xml
> +  ~ Copyright 2023 Crown Copyright
Should this be '2022-2023?'

2023-01-23 15:27 UTC, GCHQDeveloper314 commented on code-style/spotbugs-exclude.xml
> +  ~ Copyright 2023 Crown Copyright
Yes it should.

2023-01-23 15:32 UTC, t92549 approved these changes

2023-01-24 08:52 UTC, GCHQDev404 approved these changes

2023-01-24 11:41 UTC, lb324567 requested changes

2023-01-24 11:41 UTC, lb324567 commented on code-style/spotbugs-exclude.xml
> +  ~ Copyright 2023 Crown Copyright
```suggestion
  ~ Copyright 2022-2023 Crown Copyright
```

2023-02-08 11:16 UTC, merged